# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analysis:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'create-pull-request/patch'
        path: 'patch-path'
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        path: 'master-path'
    - run: ls

    - name: 'Print manual run reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo 'Reason: ${{ github.event.inputs.reason }}'
    - name: .NET code metrics
      id: this-app
      uses: ./ # do not know why it worked also with ./ngit?
      env:
        GREETINGS: 'Hello, .NET developers!' 
      with:
        owner: ${{ github.repository_owner }}
        name: ${{ github.repository }}
        branch: ${{ github.ref }}
        dir: ${{ './' }}
        repository: ${{ 'git://api.github.com/repos/RijadGerguri/CourseApi/zipball' }}
        token: ${{ secrets.TOKEN }}
      
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.4.1
      if: ${{ steps.this-app.outputs.updated-metrics }} == 'true'
      with:
        title: '${{ steps.this-app.outputs.summary-title }}'
        body: '${{ steps.this-app.outputs.summary-details }}'
        commit-message: '.NET code metrics, automated pull request.'
